# Generated by Django 4.2.6 on 2023-10-14 01:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id_person', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=200)),
                ('second_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('last_name2', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Spent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_registered', models.DateField(default=django.utils.timezone.now)),
                ('hour_registered', models.TimeField(default=django.utils.timezone.now)),
                ('amount', models.IntegerField()),
                ('type', models.CharField(max_length=200)),
                ('observation', models.CharField(max_length=200)),
                ('id_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UBapp.person')),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_registered', models.DateField(default=django.utils.timezone.now)),
                ('hour_registered', models.TimeField(default=django.utils.timezone.now)),
                ('amount', models.IntegerField()),
                ('type', models.CharField(max_length=200)),
                ('observation', models.CharField(max_length=200)),
                ('id_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UBapp.person')),
            ],
        ),
    ]
